### PR TITLE
feat: support deleting mod in grid view

### PR DESCRIPTION
**Pull request by yuukidach**
support `Delete Mod` button in grid view

image

### CODE REVIEW

**Comment by Jorixon** [comment]
I think adding a delete mods dialog with a confirmation could be a good idea, just to avoid instances the user accidentally clicks the delete mod button instead of the option above. Even though the `DeleteModBySkinEntryId()` by default moves the mod the recycle bin I don't think it's that obvious for the user.

Something similar to the delete dialog on the detailed view. Perhaps a smaller version?

**Comment by yuukidach** [comment]
Hi @Jorixon ,

Thanks for the suggestion. I have made some changes to he PR:
1. If user clicks on the delete button, a dialog will pop up
2. The user can check the "Do not show again" checkbox to avoid frequent confirmations.

Here is an example image
image

**Comment by Jorixon** [comment]
Nice! I'll do a quick test and code review tomorrow

Ui looks good 👍

**Review by Jorixon — COMMENTED** [review]
To be more consistent with the current code base we dont need to use 'this' unless it is necessary.

**Comment by yuukidach** [comment]
All comments in the CR has beed resolved, please have a look again @Jorixon

**Pull request merged**
