### PR TITLE
feat: Added zzz support

### PR DESCRIPTION
**Pull request by Jorixon**

### CODE REVIEW

**Comment by Pyrageis** [comment]
I have no idea what I did but I definitely messed up something during the merge and none of the characters are showing up, tried to figure it out but couldn't, could you take a look at it? its in main of my fork

**Comment by Pyrageis** [comment]
had a comment, deleted cause I figured it out, turned out I didnt so im posting it again
I fucked something up during the merge, no idea what, could you take a look, its in main of my fork

**Comment by Jorixon** [comment]
Pushed up a fix to your fork. It crashed when trying to read the rarity value as it was a string which gave a type mismatch when deserializing.

I still haven't tried ZZZ yet, but I did some quick testing, and it looks like everything works as it should on your fork

**Comment by Pyrageis** [comment]
> Pushed up a fix to your fork. It crashed when trying to read the rarity value as it was a string which gave a type mismatch when deserializing.
> 
> I still haven't tried ZZZ yet, but I did some quick testing, and it looks like everything works as it should on your fork

ah that makes sense, I remember I tried putting in A and S instead of 4 and 5 and changed it back after it didnt work but forgot it wasnt a string before

**Pull request merged**
