### PR TITLE
Add sort options to character gallery view

### PR DESCRIPTION
**Pull request by jeffvli**
## Preview
image

---

Adds sort options to the character gallery view to mirror functionality with detailed view
- Sort by "Enabled"
- Sort by "Date Added"
- Sort by "Folder Name"
- Sort by "Name"

### CODE REVIEW

**Comment by Jorixon** [comment]
Nice addition! I have some thoughts on this I'd like to discuss first

1.

I feel like the enabled mod(s) should always be the first item(s). This isn't how it works currently in the released version. The reason is that in most cases you only have one mod enabled. With many mods it can be hard to see if any mods are enabled as you may have to scroll all the way down. A possible solution could be to remove the 'enabled' sorting option. Then in the code after filtering switch run some extra logic that puts enabled mods at the beginning of the list. Something something pseudo code like this:

```csharp
//  private void ResetContent()

switch (SelectedSortingMethod)
{
 // ... sorting logic
}


var enabledMods = gridItemVms.where(m => m.isenabled); // Get sorted enabled mods


for each mod in enabledMods.Reverse() 
{
gridItemsVms.Remove(mod );
gridItemsVms.Insert(0, mod);
}
```
If we do decide to do this then I'd like to get this implemented before merging

2.

This second part is a bit more complicated and doesn't provide too much value for the user atm but is nice for the code base. If possible, it would be nice to reuse the `SortingMethod` (naming is hard) and `Sorter` code from the Character overview page. I like it's api surface and it's a bit more flexible imo. The problem is that it's currently hard coded for another view model type which isn't ideal. In the long run it would be best to make it generic so we can reuse it. 

These classes currently reside in `JASM\src\GIMI-ModManager.WinUI\ViewModels\CharactersViewModel.cs`. But if they are made more generic then they could be moved to the helper folder `JASM\src\GIMI-ModManager.WinUI\Helpers`

Implementing this would likley require some changes to `CharactersViewModel.cs` as well.

This isn't a blocker for me, so we don't have to do this right now, but in the long run if you dont do it then I'll probably do it later. Or at least give it an attempt ;)

**Comment by Jorixon** [comment]
I was originally thinking just keep the current order when toggling a mod.

Calling resetcontent when toggling a mod might be a bit much. Haven't tested it myself, but it might be confusing if you toggle a mod and it suddenly disappears -> gets moved up or down depending on sort method. But at the same time it could be confusing if you enable a mod then filter/reorder -> now it's at the top instead. Might just be confusing the first time though

I'll do a quick test myself tomorrow just to get a feel for it. Maybe I'm overthinking this and we could keep it as is.

**Comment by Jorixon** [comment]
Tried both the current and my suggested method, and both feel fine so we can keep it as if you want.

**Comment by jeffvli** [comment]
After my testing I ended up leaving out the re-sort when enabling/disabling mods. If you potentially have hundreds of mods for a single character it may get annoying if you want to quickly enable/disable a single mod.

Implementing reusability may take a while since I'm not yet fully familiar with the scope of changes necessary for the other pages. If you're ok with merging this now and refactoring later, this PR is ready.

**Review by Jorixon — APPROVED** [review]

**Pull request merged**
